
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemaperfect_ package provides tools for auto-generation of Python
APIs from JSONSchema_ specifications.

See more information in the README_.

.. _README: https://github.com/jwilson8767/schemaperfect/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _schemaperfect: https://github.com/jwilson8767/schemaperfect
"""
short_version = '0.5.0'
version = '0.5.0'
full_version = '0.5.0'
git_revision = '2c455d61a9566470f79f447d4e3899d18d287149'
release = True
if not release:
    version = full_version
