
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemaperfect_ package provides tools for auto-generation of Python
APIs from JSONSchema_ specifications.

See more information in the README_.

.. _README: https://github.com/jwilson8767/schemaperfect/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _schemaperfect: https://github.com/jwilson8767/schemaperfect
"""
short_version = '0.4.4'
version = '0.4.4'
full_version = '0.4.4.dev0+c56ec67'
git_revision = 'c56ec67f09037879398ac421c6e067e191d0512f'
release = False
if not release:
    version = full_version
