
# This file is automatically generated by the setup.py script
long_description = """
JSONSchema API Generator
========================
The schemaperfect_ package provides tools for auto-generation of Python
APIs from JSONSchema_ specifications.

See more information in the README_.

.. _README: https://github.com/jwilson8767/schemaperfect/blob/master/README.md
.. _JSONSchema: http://json-schema.org/
.. _schemaperfect: https://github.com/jwilson8767/schemaperfect
"""
short_version = '0.4.2'
version = '0.4.2'
full_version = '0.4.2'
git_revision = 'c02e49963853d9c99685c74e5cba1193505e2046'
release = True
if not release:
    version = full_version
